//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_StorePhone3.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class brand
    {
        public brand()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Tên nhà sản xuất không được trống")]
        [Display(Name = "BrandName")]
        public string name { get; set; }
        [Required(ErrorMessage = "Logo không được trống")]
        [Display(Name = "BrandLogo")]
        public string logo { get; set; }
        public int activeFlag { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
